% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
\PassOptionsToPackage{dvipsnames,svgnames,x11names}{xcolor}
%
\documentclass[
]{estat/estat}

\usepackage{amsmath,amssymb}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else  
    % xetex/luatex font selection
    \setmainfont[]{Arial}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\usepackage[left=3cm,right=2cm,top=3cm,bottom=2cm]{geometry}
\setlength{\emergencystretch}{3em} % prevent overfull lines
\setcounter{secnumdepth}{5}
% Make \paragraph and \subparagraph free-standing
\makeatletter
\ifx\paragraph\undefined\else
  \let\oldparagraph\paragraph
  \renewcommand{\paragraph}{
    \@ifstar
      \xxxParagraphStar
      \xxxParagraphNoStar
  }
  \newcommand{\xxxParagraphStar}[1]{\oldparagraph*{#1}\mbox{}}
  \newcommand{\xxxParagraphNoStar}[1]{\oldparagraph{#1}\mbox{}}
\fi
\ifx\subparagraph\undefined\else
  \let\oldsubparagraph\subparagraph
  \renewcommand{\subparagraph}{
    \@ifstar
      \xxxSubParagraphStar
      \xxxSubParagraphNoStar
  }
  \newcommand{\xxxSubParagraphStar}[1]{\oldsubparagraph*{#1}\mbox{}}
  \newcommand{\xxxSubParagraphNoStar}[1]{\oldsubparagraph{#1}\mbox{}}
\fi
\makeatother


\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}\usepackage{longtable,booktabs,array}
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother

\usepackage{booktabs}
\usepackage{longtable}
\usepackage{array}
\usepackage{multirow}
\usepackage{wrapfig}
\usepackage{float}
\usepackage{colortbl}
\usepackage{pdflscape}
\usepackage{tabu}
\usepackage{threeparttable}
\usepackage{threeparttablex}
\usepackage[normalem]{ulem}
\usepackage{makecell}
\usepackage{xcolor}
\authors{%
    João Gabriel Bertoli Rola\\

    
}

% escreva o nome do cliente aqui
% se for mais de um separe por \\
\client{%
    João Victor Neves
}
% Baixando pacotes
\RequirePackage{fancyhdr}
\RequirePackage{graphicx}

\setlength\headheight{28pt}  

\setlength{\parindent}{15pt} % Adiciona indentação nos parágrafos
\setlength{\parskip}{0pt} % Adiciona 0 espaço entro os parágrafos

\newcommand{\estat}{\textbf{ESTAT}\xspace}
\newcommand{\direx}{\textbf{DIREX}\xspace}
\makeatletter
\@ifpackageloaded{caption}{}{\usepackage{caption}}
\AtBeginDocument{%
\ifdefined\contentsname
  \renewcommand*\contentsname{Índice}
\else
  \newcommand\contentsname{Índice}
\fi
\ifdefined\listfigurename
  \renewcommand*\listfigurename{Lista de Figuras}
\else
  \newcommand\listfigurename{Lista de Figuras}
\fi
\ifdefined\listtablename
  \renewcommand*\listtablename{Lista de Tabelas}
\else
  \newcommand\listtablename{Lista de Tabelas}
\fi
\ifdefined\figurename
  \renewcommand*\figurename{Figura}
\else
  \newcommand\figurename{Figura}
\fi
\ifdefined\tablename
  \renewcommand*\tablename{Tabela}
\else
  \newcommand\tablename{Tabela}
\fi
}
\@ifpackageloaded{float}{}{\usepackage{float}}
\floatstyle{ruled}
\@ifundefined{c@chapter}{\newfloat{codelisting}{h}{lop}}{\newfloat{codelisting}{h}{lop}[chapter]}
\floatname{codelisting}{Listagem}
\newcommand*\listoflistings{\listof{codelisting}{Lista de Listagens}}
\captionsetup{labelsep=colon}
\makeatother
\makeatletter
\makeatother
\makeatletter
\@ifpackageloaded{caption}{}{\usepackage{caption}}
\@ifpackageloaded{subcaption}{}{\usepackage{subcaption}}
\makeatother

\ifLuaTeX
\usepackage[bidi=basic]{babel}
\else
\usepackage[bidi=default]{babel}
\fi
\babelprovide[main,import]{portuguese}
\ifPDFTeX
\else
\babelfont{rm}[]{Arial}
\fi
% get rid of language-specific shorthands (see #6817):
\let\LanguageShortHands\languageshorthands
\def\languageshorthands#1{}
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\usepackage{bookmark}

\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same} % disable monospaced font for URLs
\hypersetup{
  pdftitle={House of Excellence},
  pdflang={pt},
  colorlinks=true,
  linkcolor={black},
  filecolor={black},
  citecolor={black},
  urlcolor={black},
  pdfcreator={LaTeX via pandoc}}


\title{House of Excellence}
\author{}
\date{}

\begin{document}
\maketitle

% Limpando tudo
\fancyhf{} 

% Ajustes do header
\fancyhead[L]{} % limpando o lado esquerdo
\fancyhead[R]{\includegraphics[width=0.20\textwidth]{estat/imagens/estat.png}} % adicionando logo no canto direito
\renewcommand{\headrulewidth}{0pt}   % sem linha embaixo da logo

% Ajustes de fim de página
\fancyfoot[R]{\textcolor{white}{\thepage}} % Número em branco no canto direito

% Aplicando o estilo que acabamos de criar
\pagestyle{fancy} 

\renewcommand*\contentsname{Sumário}
{
\hypersetup{linkcolor=}
\setcounter{tocdepth}{3}
\tableofcontents
}

\section{Introdução}\label{introduuxe7uxe3o}

\section{Referencial Teórico}\label{referencial-teuxf3rico}

\section{Análises}\label{anuxe1lises}

\subsection{Analise 1}\label{analise-1}

\subsubsection{TOP 5 PAÍSES MEDALHISTAS DAS OLIMPIADAS DE SYDNEY(2000) -
RIO DE JANEIRO
(2016)}\label{top-5-pauxedses-medalhistas-das-olimpiadas-de-sydney2000---rio-de-janeiro-2016}

Nessa primeira analise a variavel analisada é quantitativa discreta
(eixo y) pois vamos contabilizar quantas medalhas cada país ganhou
apenas entre as mulheres durante 5 ciclos olimpicos e a varivel dos
países (eixo x) é quantitativa nominal por ser nomes de países e
objetivo dessa analise é entender quais são os países com mais melalhas
entre as mulheres durante esse espaço de tempo de 5 olimpiadas.

\includegraphics{template-relatorio_files/figure-pdf/unnamed-chunk-2-1.pdf}

\begin{verbatim}

Estados Unidos         Russia          China      Australia       Alemanha 
           741            416            384            340            268 
\end{verbatim}

Com o gráfico e a tabela conseguimos analisar a força dos Estados Unidos
entre as mulheres se mostrando o país com mais medalhas contabilizando
741 mais de 300 medalhas a frente do segundo país que aparece que é a
Russia com 416 medalhas logo deposi vem a China com 384 medalhas e com
44 medalhas atras em 4 no top de medalhas desses 5 cilcos olimpicos a
Australia que dessas 5 olimpiadas foi o primeiro país a sediar em 2000 e
no geral obteve suas 340 medalhas e a Alemanha em 5 com 268 medalhas
quase 100 medalhas atras da Australia.

\subsection{Analise 2}\label{analise-2}

\subsubsection{ANALISANDO IMC EM DIFERENTES
ESPORTES}\label{analisando-imc-em-diferentes-esportes}

Nessa analise o dado em questão é o IMC que é uma variavel quantitativa
continua. Esta analise vai ser apresentado um boxplot com 5 esportes
Judo, Badminton, Futebol, Ginastica e Atletismo, onde será avaliado o
indice de IMC entre cada um deles e se tem diferença entre cada esporte.

\includegraphics{template-relatorio_files/figure-pdf/unnamed-chunk-3-1.pdf}

\begin{quadro}[H]
\caption{Medidas resumo dos esportes}
\centering
\begin{tabular}{| l |
            S[table-format = 2.2]
            S[table-format = 1.2]
            S[table-format = 2.2]
            S[table-format = 2.2]
            S[table-format = 2.2]
            |}
    \toprule
        \textbf{Estatística} & \textbf{Atletismo} & \textbf{Badminton} & \textbf{Futebol} & \textbf{Ginastica} & \textbf{Judo} \\
        \midrule
        Média & 22.30 & 22.21 & 22.51 & 20.68 & 25.70 \\
        Desvio Padrão & 3.86 & 1.50 & 1.73 & 2.38 & 5.12 \\
        Variância & 14.92 & 2.26 & 2.99 & 5.67 & 26.23 \\
        Mínimo & 15.82 & 18.94 & 16.73 & 15.16 & 18.52 \\
        1º Quartil & 20.03 & 21.22 & 21.34 & 18.61 & 22.06 \\
        Mediana & 21.45 & 22.28 & 22.49 & 21.09 & 24.68 \\
        3º Quartil & 23.67 & 23.21 & 23.71 & 22.48 & 27.70 \\
        Máximo & 44.38 & 26.73 & 29.07 & 26.45 & 56.50 \\
    \bottomrule
    \end{tabular}
    
\end{quadro}

O grafico apresenta dados interessantes para serem apresentados.
Primeiro o Judo que apresenta alguns outliers mas devido que o esporte é
separado por peso e isso afeta diretamente o imc pois sendo mais pesado
tende a afetar diretamente o imc. O atletismo tem muitos outliers com
imcs acima do padrão para o esporte mas devido a alguns esportes de
força que geralmente apresentam pessoas com pesos maiores e causa esse
tanto de outliers em questão e a sua média e menor do que a do judo. O
badminton por sua vez mostra os números de imc são muitos proximos tendo
seu boxplot bem pequeno o que demontra uniformidade nos dados. O futebol
demonstra outliers para ambos os lados o que mostra a diferença do peso
no esporte mas ainda é um boxplot bastante pequeno que mostra a
uniformidade dos dados também mas apresenta uma maior variedade dos
dados do que no badminton por exemplo. A ginastica é o esporte que
apresenta os menores imc entre os boxplots onde a média é muito proxima
de 20.

\subsection{Analise 3}\label{analise-3}

\subsubsection{TOP 3 MEDALHISTAS DAS OLIMPIADAS
2000-2016}\label{top-3-medalhistas-das-olimpiadas-2000-2016}

\includegraphics{template-relatorio_files/figure-pdf/unnamed-chunk-6-1.pdf}

No top 3 medalhistas das Olimpíadas de Sydney 2000 até Rio 2016, temos
Michael Phelps em primeiro lugar com um total de 28 medalhas, seguido
por outros dois atletas empatados com 12 medalhas cada. Todos os três
atletas praticam natação, evidenciando que este é um dos esportes onde
os competidores têm maior possibilidade de acumular medalhas. Isso se
deve ao fato de que, na natação, as categorias não são definidas por
peso, mas sim pelos diferentes estilos de nado, o que permite aos
atletas competirem em várias modalidades. A análise detalhada dos três
principais medalhistas revela que a maioria de suas conquistas é de
medalhas de ouro, totalizando 32 medalhas, o que corresponde a 61,53\%
das medalhas entre eles. Em sequência, esses atletas conquistaram 10
medalhas de prata e 10 de bronze. Esses dados sugerem uma clara
tendência entre os medalhistas mais bem-sucedidos em conquistar medalhas
de ouro, destacando o alto nível competitivo desses atletas. Dessa
forma, observa-se uma relação entre ser um dos medalhistas de maior
sucesso e a predominância de medalhas de ouro em suas conquistas.

\subsection{Analise 4}\label{analise-4}

Esta análise irá mostrar a relação entre altura (em centímetros) e peso
(em quilos), sendo ambas as variáveis quantitativas contínuas. Todos os
atletas analisados nesta pesquisa são medalhistas das Olimpíadas de
Sydney 2000 e Rio 2016. Para analisar a correlação entre as duas
variáveis, utilizou-se o cálculo do coeficiente de correlação de
Pearson.

\includegraphics{template-relatorio_files/figure-pdf/unnamed-chunk-7-1.pdf}

O coeficiente de Pearson calculado foi de \textbf{0.8053352}, indicando
uma forte correlação positiva entre peso e altura, o que confirma a
tendência de que, à medida que a altura dos atletas aumenta, o peso
também tende a aumentar. No entanto, é importante ressaltar que alguns
dos pesos mais altos estão associados a alturas relativamente baixas.
Isso sugere que, embora haja uma tendência de correlação positiva, uma
altura maior não implica necessariamente um peso maior. Em resumo, o
gráfico revela uma relação significativa entre peso e altura, mas outros
fatores, como composição corporal e características individuais, também
desempenham um papel importante na determinação do peso dos atletas. \#
Conclusões




\end{document}
